import Link from "next/link";
import { PolicyLinks } from "./PolicyLinks";
import { PageHeader } from "../../../components/ui/PageHeader";

export const metadata = { title: "Preguntas frecuentes", description: "Resuelve tus dudas sobre productos originales, pedidos, pagos, apartados y entregas de Luxury Finds." };

const questions = [
  { question: "¿Dónde adquieren sus productos?", answer: "Adquirimos nuestros productos directamente en los sitios web de las marcas, sus distribuidores oficiales y sus tiendas físicas." },
  { question: "¿Cuánto tiempo tardan en procesar mi compra?", answer: "Los productos bajo pedido se adquieren una vez realizada y pagada tu orden. Su procesamiento tarda aproximadamente de 20 a 30 días hábiles, de lunes a viernes, sin contar días festivos de México y Estados Unidos. A este plazo se suma el tiempo de empaquetado y preparación. Algunos artículos tienen plazos especiales, que se indican en su descripción." },
  { question: "¿Cuentan con productos para entrega inmediata?", answer: <>Sí. Encuentra nuestro stock disponible físicamente en La Paz en <Link href="/entrega-inmediata">Entrega inmediata</Link>. Los artículos de <Link href="/productos-en-camino">Productos en camino</Link> todavía no están disponibles para entrega inmediata.</> },
  { question: "¿Qué hago si quiero un producto que no aparece en la página?", answer: <>Escríbenos por mensaje directo en <a href="https://instagram.com/luxuryfindsmx">Instagram, @luxuryfindsmx</a>, para que podamos cotizártelo.</> },
  { question: "¿Qué servicio de paquetería utilizan?", answer: "Utilizamos DHL Express y también realizamos envíos mediante Mercado Libre. Para entregas locales contamos con DiDi Entregas, con costo extra." },
  { question: "¿Puedo hacer un cambio o devolución?", answer: "Por la naturaleza de los productos y por cuestiones de higiene, no aceptamos cambios ni devoluciones por elección del cliente. Si Luxury Finds no puede conseguir el producto de tu plan de pagos, puedes elegir otro producto disponible, un modelo diferente o solicitar la devolución del monto abonado." },
  { question: "¿Qué métodos de pago aceptan?", answer: "Aceptamos transferencia, depósito, efectivo y retiro sin tarjeta." },
  { question: "¿Hacen entregas locales en La Paz?", answer: "Sí. Puedes recoger en Indeco de 8:30 a. m. a 12:30 p. m. o en Villas del Encanto de 4:00 p. m. a 9:00 p. m. Avisa con anticipación por WhatsApp o mensaje directo y espera nuestra confirmación antes de pasar. También ofrecemos DiDi Entregas con costo extra." },
  { question: "¿Qué significa pre-order o bajo pedido?", answer: "Son productos que adquirimos especialmente para ti después de realizar y pagar tu orden. El tiempo estimado de llegada es de 20 a 30 días hábiles. Depende de la disponibilidad de la marca, sus distribuidores, las paqueterías y la logística. Revisa la descripción de cada producto para conocer cualquier plazo especial." },
  { question: "¿Cómo funcionan los apartados?", answer: "El apartado se registra con Luxury Finds y requiere un anticipo del 50% del total, salvo que acordemos otro monto contigo. Tienes un mes desde la fecha del apartado para liquidar. Puedes abonar antes del vencimiento. Si no liquidas a tiempo, el producto se libera y pasa a disponible; no se reembolsa el anticipo ni se entrega el producto. Una vez iniciado, no se permiten cambios de artículo." },
  { question: "¿Cómo funcionan los planes de pago semanales?", answer: "Ofrecemos planes de 4 a 16 semanas. El total depende del artículo y del plazo elegido, y puede ser mayor en los planes más largos. Paga el mismo día de la semana en que se generó el pedido. Un pago fuera de esa fecha genera una multa de $100 MXN. Puedes adelantar pagos o liquidar antes, manteniendo el total pactado." },
  { question: "¿Cuándo recibo mi producto en un plan de pagos?", answer: "Si está en stock, se entrega después de liquidar el total. Si es bajo pedido, se ordena en el penúltimo pago y el tiempo de entrega depende del proveedor y la paquetería. Si no está disponible en ese momento, puedes elegir otro producto, otro modelo o solicitar la devolución de lo abonado." },
];

const policies = [
  { id: "pre-order", title: "Productos bajo pedido", paragraphs: ["Revisa el tiempo estimado antes de comprar: normalmente es de 20 a 30 días hábiles, excluyendo festivos de México y Estados Unidos, más preparación y empaquetado. Los productos con certificados de canje u otras características especiales pueden tener un plazo mayor, indicado en su descripción.", "Una vez realizado el pago no se permiten cambios de productos ni cancelaciones por elección del cliente."] },
  { id: "apartados", title: "Condiciones de los apartados", paragraphs: ["Anticipo del 50% y un mes para liquidar, salvo otro monto acordado con Luxury Finds. Si vence el plazo sin liquidar, el producto pasa a disponible. El incumplimiento no da lugar a reembolso del anticipo ni a la entrega del artículo.", "Puedes adelantar abonos. Una vez iniciado el apartado no se permiten cambios de artículo. La entrega de productos en stock se coordina al liquidar; los productos en camino deben llegar antes de entregarse."] },
  { id: "planes", title: "Planes de pagos", paragraphs: ["Elige de 4 a 16 semanas y consulta el total de tu plan antes de iniciarlo. Los pagos se realizan el mismo día de la semana del pedido; el retraso genera una multa de $100 MXN. Pagar antes no reduce el total acordado.", "Dos semanas consecutivas de retraso o la decisión de no continuar implican que no se entrega el producto ni se reembolsa lo abonado. No se permite modificar o cancelar la orden una vez iniciado el plan.", "Los productos en stock se entregan al liquidar. Los de pedido se ordenan en el penúltimo pago; si no están disponibles, puedes elegir otro producto, otro modelo o solicitar la devolución de lo abonado. El primer pago confirma la aceptación de las condiciones del plan."] },
  { id: "entregas", title: "Entregas locales", paragraphs: ["Indeco: de 8:30 a. m. a 12:30 p. m. Villas del Encanto: de 4:00 p. m. a 9:00 p. m. Avisa con anticipación por WhatsApp o mensaje directo y espera confirmación.", "DiDi Entregas tiene costo extra. Revisa tu dirección, nombre y teléfono, mantente atento a las notificaciones y asegúrate de poder recibir al mensajero. Una entrega fallida puede generar costos adicionales de reprogramación."] },
  { id: "envios", title: "Envíos y DiDi Entregas", paragraphs: ["Realizamos envíos con DHL Express y Mercado Libre. Las entregas locales mediante DiDi Entregas son una alternativa a recoger en nuestros puntos.", "Según las condiciones del servicio de Luxury Finds, al elegir DiDi Entregas el cliente asume los riesgos del traslado. Luxury Finds no se responsabiliza por pérdidas, extravíos, daños o robos después de entregar el pedido a la plataforma, ni por incidencias causadas por datos incorrectos o falta de atención al mensajero."] },
  { id: "resguardo", title: "Productos pagados y guardados", paragraphs: ["Los productos totalmente pagados pueden mantenerse en resguardo temporal cuando estén recibidos o disponibles. El plazo máximo indicado es de un mes natural desde la fecha de la orden para recoger, solicitar entrega local o pagar el envío nacional.", "Si vence el plazo sin recoger, notificar una situación o pagar el envío, Luxury Finds podrá disponer nuevamente de los productos para su venta. Da seguimiento a tu pedido y sus plazos.", "Durante el resguardo, los productos se mantienen en un espacio adecuado. Luxury Finds no se responsabiliza por deterioro natural o variaciones derivadas del paso del tiempo."] },
  { id: "cancelaciones", title: "Cancelaciones", paragraphs: ["Luxury Finds puede cancelar pedidos cuando un producto bajo pedido no esté disponible, cuando detecte un pedido o pago fraudulento, o cuando se elija efectivo y no se realice y comparta el comprobante en las 24 horas naturales posteriores al pedido.", "También puede suspender compras por incumplimiento de sus condiciones. En planes de pago, si el producto no está disponible al realizar el penúltimo pago, se ofrecen las alternativas indicadas en la sección de planes."] },
  { id: "terminos", title: "Términos y condiciones", paragraphs: ["Luxury Finds es la empresa distribuidora y comercializadora; el usuario es el cliente o comprador. Al realizar una compra, el cliente acepta las condiciones de la modalidad elegida y debe revisar sus tiempos y plazos.", "Los precios y las condiciones pueden cambiar. Los datos personales solicitados se utilizan para la venta y, cuando corresponde, para coordinar la entrega o envío con terceros."] },
];

export default function HowToPage() {
  return <main className="faq-page"><div className="shell">
    <PageHeader eyebrow="ESTAMOS PARA AYUDARTE" title={<>Resolvemos tus <em>dudas.</em></>} description="Todo lo que necesitas saber para elegir, pagar y recibir tus hallazgos." />
    <div className="faq-layout">
      <div className="faq-main">
        <section className="faq-panel" aria-labelledby="faq-title"><h2 id="faq-title">Preguntas frecuentes</h2><div className="faq-questions">{questions.map(item => <details className="faq-item" key={item.question}><summary>{item.question}<span className="faq-toggle" aria-hidden="true" /></summary><div className="faq-answer"><p>{item.answer}</p></div></details>)}</div></section>
        <section className="faq-panel faq-policy-panel" aria-labelledby="faq-policies-title"><p className="section-label">COMPRA CON CONFIANZA</p><h2 id="faq-policies-title">Políticas y condiciones</h2>{policies.map(item => <details className="faq-item" id={item.id} key={item.id}><summary>{item.title}<span className="faq-toggle" aria-hidden="true" /></summary><div className="faq-answer">{item.paragraphs.map(text => <p key={text}>{text}</p>)}</div></details>)}</section>
      </div>
      <aside className="faq-sidebar"><section className="faq-panel"><h2>Consulta nuestras políticas y más</h2><PolicyLinks policies={policies.map(({ id, title }) => ({ id, title }))} /></section><section className="faq-panel faq-provider"><p className="section-label">LUXURY FINDS</p><h2>Hallazgos con atención cercana</h2><p>Moda y belleza, elegidas para ti. Estamos en La Paz, Baja California Sur.</p><p>Adquirimos productos de marcas, distribuidores oficiales y tiendas físicas.</p><Link href="/contacto" className="button button-primary">Contáctanos <span aria-hidden="true">→</span></Link><a className="faq-instagram" href="https://instagram.com/luxuryfindsmx">@luxuryfindsmx</a></section></aside>
    </div>
  </div></main>;
}
