import Link from "next/link";
import { requireAdminActor } from "../../../lib/supabase/business";
import { listReservations } from "../../../lib/supabase/incoming-reservations";
import { formatMoney, LOGISTICS_STATUS_LABELS } from "../../../lib/format";
import { ReservationControls } from "./ReservationControls";
export const dynamic = "force-dynamic";
const LABELS: Record<string, string> = { ACTIVE: "Pendiente de liquidar", PAID: "Liquidado", EXPIRED: "Vencido: piezas liberadas", CANCELLED: "Cancelado: piezas liberadas" };
export default async function Page({ searchParams }: { searchParams: Promise<{ pagina?: string; estado?: string }> }) {
  await requireAdminActor(); const sp = await searchParams; const page = Math.max(1, Math.floor(Number(sp.pagina) || 1));
  let result; try { result = await listReservations(page, sp.estado); }
  catch (error) { return <main className="admin-content"><h1>Apartados</h1><p className="form-message form-error" role="alert">{error instanceof Error ? error.message : "No se pudieron cargar los apartados."}</p></main>; }
  const href = (target: number) => `/admin/apartados?${new URLSearchParams({ pagina: String(target), estado: sp.estado ?? "" })}`;
  return <main className="admin-content"><div className="staff-heading"><div><h1>Apartados</h1><p className="admin-hint">Anticipo predeterminado de 50 %, ajustable por ti. Un mes para liquidar; después se libera la pieza y se notifica a la clienta.</p></div><Link className="button button-primary" href="/admin/proximamente">Registrar apartado</Link></div><form method="get" action="/admin/apartados" className="staff-search"><label className="sr-only" htmlFor="reservation-status">Estado</label><select className="input" name="estado" id="reservation-status" defaultValue={sp.estado ?? ""}><option value="">Todos</option>{Object.entries(LABELS).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select><button className="button button-secondary">Filtrar</button></form>
    {result.error && <p className="form-message form-error" role="alert">{result.error}</p>}<div className="incoming-admin-grid">{result.reservations.map((row) => { const ticket = row.tickets; const balance = Math.max(0, Number(ticket.agreed_total_cents) - Number(ticket.paid_principal_cents)); return <section className="admin-panel incoming-admin-card" key={row.id}><h2>{ticket.product_name_snapshot}</h2><p>{row.clients.first_name} {row.clients.last_name} · {ticket.ticket_number}</p><strong>{LABELS[row.status] ?? row.status}</strong><p>{row.quantity} pieza(s) · Total {formatMoney(Number(ticket.agreed_total_cents))} · Pagado {formatMoney(Number(ticket.paid_principal_cents))} · Saldo {formatMoney(balance)}</p><p>Vence: {new Date(row.expires_at).toLocaleString("es-MX", { timeZone: "America/Mazatlan", dateStyle: "medium", timeStyle: "short" })} · {row.stock_allocated_quantity}/{row.quantity} pieza(s) recibidas · {LOGISTICS_STATUS_LABELS[ticket.logistics_status] ?? ticket.logistics_status}</p>{row.closure_reason && <p className="admin-hint">{row.closure_reason} Los abonos permanecen en el historial para revisión.</p>}<Link href="/admin/cobranza">Ver en Cobranza</Link><ReservationControls key={`${row.id}-${ticket.paid_principal_cents}-${row.status}`} id={row.id} balance={balance} canPay={row.status === "ACTIVE" && balance > 0} canCancel={["ACTIVE", "PAID"].includes(row.status) && ticket.logistics_status !== "DELIVERED"} requestId={crypto.randomUUID()} /></section>; })}</div>
    {!result.error && !result.reservations.length && <p>No hay apartados en este estado.</p>}<div className="admin-form-actions">{page > 1 && <Link href={href(page - 1)}>Anterior</Link>}{result.hasNext && <Link href={href(page + 1)}>Siguiente</Link>}</div>
  </main>;
}
