"use client";
import { useActionState } from "react";
import { emptyActionState } from "../../../lib/actions";
import { centsToInput } from "../../../lib/format";
import { payReservationAction, cancelReservationAction } from "./actions";
export function ReservationControls({ id, balance, canPay, canCancel, requestId }: { id: string; balance: number; canPay: boolean; canCancel: boolean; requestId: string }) {
  const [payment, pay, paying] = useActionState(payReservationAction, emptyActionState);
  const [cancelled, cancel, cancelling] = useActionState(cancelReservationAction, emptyActionState);
  return <>{canPay && <details><summary className="button button-primary button-small">Registrar abono</summary><form className="dialog-form" action={pay}><input type="hidden" name="id" value={id} /><input type="hidden" name="requestId" value={requestId} /><label className="field"><span>Abono recibido (MXN)</span><input className="input" name="amount" inputMode="decimal" defaultValue={centsToInput(balance)} required /></label><label className="field"><span>Método confirmado</span><select className="input" name="method"><option value="CASH">Efectivo</option><option value="TRANSFER">Transferencia confirmada</option></select></label><label className="field"><span>Referencia</span><input className="input" name="reference" maxLength={300} /></label>{payment.error && <p className="form-message form-error" role="alert">{payment.error}</p>}{payment.success && <p className="form-message form-success" role="status">{payment.success}</p>}<button className="button button-primary" disabled={paying || Boolean(payment.success)}>{paying ? "Registrando…" : "Confirmar abono"}</button></form></details>}
    {canCancel && <details><summary className="button button-secondary button-small">Cancelar apartado</summary><form className="dialog-form" action={cancel}><input type="hidden" name="id" value={id} /><p className="admin-hint">Se liberan las piezas. Los abonos quedan registrados para que decidas cómo resolverlos.</p><label className="field"><span>Motivo</span><textarea className="input" name="reason" maxLength={1000} required /></label>{cancelled.error && <p className="form-message form-error" role="alert">{cancelled.error}</p>}{cancelled.success && <p className="form-message form-success" role="status">{cancelled.success}</p>}<button className="button button-danger" disabled={cancelling || Boolean(cancelled.success)}>{cancelling ? "Cancelando…" : "Confirmar cancelación y liberar"}</button></form></details>}</>;
}
