(function(global){'use strict';
const data=global.GlamData;
const store=data.storage;
const keys={tickets:'tickets',plans:'paymentPlans',schedules:'scheduledPayments',payments:'payments',proofs:'paymentProofs',credits:'creditMovements',refunds:'refunds',templates:'paymentPlanTemplates'};
const get=k=>store.get(keys[k],[]);const save=(k,v)=>store.set(keys[k],v);
const nextId=list=>list.length?Math.max(...list.map(x=>Number(x.id)||0))+1:1;
const cents=value=>Math.round((Number(value)||0)*100);
const moneyValue=value=>Number((Number(value||0)/100).toFixed(2));
const isoDate=value=>(value||new Date().toISOString()).slice(0,10);
const today=()=>isoDate();
function addDays(date,days){const d=new Date(date+'T12:00:00');d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)}
function dayDiff(from,to=today()){return Math.max(0,Math.floor((new Date(to+'T12:00:00')-new Date(from+'T12:00:00'))/86400000))}
function orderSnapshot(order){return (order.products||[]).map(item=>({orderItemId:item.id,productId:item.catalogProductId||null,name:item.name,variant:item.variant||{},quantity:Number(item.quantity)||1,originalUnitPriceCents:cents(item.unitPrice),discountCents:0,finalUnitPriceCents:cents(item.unitPrice),subtotalCents:cents(item.subtotal||(item.quantity||1)*(item.unitPrice||0)),cancelled:item.status==='cancelled'}))}
function activeSubtotal(ticket){return ticket.itemsSnapshot.filter(i=>!i.cancelled).reduce((sum,i)=>sum+Number(i.subtotalCents||0),0)}
function paymentsFor(ticketId){return get('payments').filter(p=>p.ticketId===ticketId)}
function refundsFor(ticketId){return get('refunds').filter(r=>r.ticketId===ticketId)}
function amountPaidCents(ticketId){return paymentsFor(ticketId).reduce((s,p)=>s+p.amountCents,0)-refundsFor(ticketId).reduce((s,r)=>s+r.amountCents,0)}
function creditAppliedCents(ticketId){return get('credits').filter(m=>m.destinationTicketId===ticketId&&m.type==='credit_applied').reduce((s,m)=>s+m.amountCents,0)}
function creditedFromTicketCents(ticketId){return get('credits').filter(m=>m.sourceTicketId===ticketId&&m.type==='credit_created').reduce((s,m)=>s+m.amountCents,0)}
function calculate(ticket){const subtotal=activeSubtotal(ticket);const total=Math.max(0,subtotal-Number(ticket.discountTotalCents||0)+Number(ticket.surchargeTotalCents||0));const paid=Math.max(0,amountPaidCents(ticket.id));const creditApplied=creditAppliedCents(ticket.id);const balance=Math.max(0,total-paid-creditApplied);const excess=Math.max(0,paid+creditApplied-total-creditedFromTicketCents(ticket.id));return{subtotalCents:subtotal,totalCents:total,amountPaidCents:paid,creditAppliedCents:creditApplied,balanceDueCents:balance,unresolvedExcessCents:excess}}
function overdueSchedules(ticketId){refreshSchedules();return get('schedules').filter(s=>s.ticketId===ticketId&&s.status==='overdue')}
function financialStatus(ticket){const c=calculate(ticket);if(ticket.status==='cancelled')return'cancelled';if(ticket.status==='refunded')return'refunded';if(c.balanceDueCents===0)return'paid';if(overdueSchedules(ticket.id).length)return'overdue';if(ticket.paymentPlanId)return'payment_plan';if(c.amountPaidCents+c.creditAppliedCents>0)return'partial';return'unpaid'}
function persistTicket(ticket){const c=calculate(ticket);Object.assign(ticket,c,{subtotal:moneyValue(c.subtotalCents),total:moneyValue(c.totalCents),amountPaid:moneyValue(c.amountPaidCents),balanceDue:moneyValue(c.balanceDueCents),creditApplied:moneyValue(c.creditAppliedCents),financialStatus:financialStatus(ticket),updatedAt:new Date().toISOString()});const list=get('tickets');const i=list.findIndex(t=>t.id===ticket.id);if(i>=0)list[i]=ticket;else list.push(ticket);save('tickets',list);return ticket}
function nextFolio(){const year=new Date().getFullYear();const key=`luxuryfinds_ticket_counter_${year}`;const number=Number(localStorage.getItem(key)||0)+1;localStorage.setItem(key,String(number));return`LF-${year}-${String(number).padStart(4,'0')}`}
function createTicketFromOrder(order){const existing=get('tickets').find(t=>t.orderId===order.id);if(existing)return persistTicket(existing);const list=get('tickets');const ticket={id:nextId(list),folio:nextFolio(),clientId:order.clientId,orderId:order.id,createdAt:order.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString(),itemsSnapshot:orderSnapshot(order),discountTotalCents:0,surchargeTotalCents:0,paymentType:'cash',paymentPlanId:null,notes:'',status:'active',isMigrated:true};list.push(ticket);save('tickets',list);return persistTicket(ticket)}
function syncTicketForOrder(orderId){const order=data.getOrders().find(o=>o.id===orderId);if(!order)return null;let ticket=get('tickets').find(t=>t.orderId===orderId);if(!ticket)return createTicketFromOrder(order);for(const snap of ticket.itemsSnapshot){const item=order.products.find(p=>String(p.id)===String(snap.orderItemId));if(item)snap.cancelled=item.status==='cancelled'}for(const item of order.products){if(!ticket.itemsSnapshot.some(s=>String(s.orderItemId)===String(item.id)))ticket.itemsSnapshot.push(orderSnapshot({products:[item]})[0])}return persistTicket(ticket)}
function setTicketDiscount(ticketId,type,value){const ticket=get('tickets').find(t=>t.id===ticketId);if(!ticket)throw new Error('Ticket no encontrado.');const subtotal=activeSubtotal(ticket);ticket.discountType=type;ticket.discountValue=Number(value)||0;ticket.discountTotalCents=type==='percent'?Math.round(subtotal*ticket.discountValue/100):cents(ticket.discountValue);return persistTicket(ticket)}
function setItemDiscount(ticketId,orderItemId,type,value){const ticket=get('tickets').find(t=>t.id===ticketId);if(!ticket)throw new Error('Ticket no encontrado.');const item=ticket.itemsSnapshot.find(i=>String(i.orderItemId)===String(orderItemId));if(!item)throw new Error('Producto no encontrado.');const original=item.originalUnitPriceCents*(item.quantity||1);item.discountType=type;item.discountValue=Number(value)||0;item.discountCents=type==='percent'?Math.round(original*item.discountValue/100):cents(item.discountValue);item.finalUnitPriceCents=Math.max(0,item.originalUnitPriceCents-Math.round(item.discountCents/(item.quantity||1)));item.subtotalCents=Math.max(0,original-item.discountCents);return persistTicket(ticket)}
function alignWeekday(date,weekday){const base=new Date(isoDate(date)+'T12:00:00'),delta=(Number(weekday)-base.getDay()+7)%7;base.setDate(base.getDate()+delta);return base.toISOString().slice(0,10)}
function createPlan(ticketId,options){let ticket=get('tickets').find(t=>t.id===ticketId);if(!ticket)throw new Error('Ticket no encontrado.');const plans=get('plans');const base=activeSubtotal(ticket)-Number(ticket.discountTotalCents||0);const surcharge=options.surchargeType==='percent'?Math.round(base*Number(options.surchargeValue||0)/100):cents(options.surchargeValue);const frequency=options.frequency||'weekly',paymentDay=options.paymentDay??null,requestedDate=isoDate(options.firstDueDate),firstDueDate=frequency==='weekly'&&paymentDay!=null?alignWeekday(requestedDate,paymentDay):requestedDate;ticket.surchargeTotalCents=surcharge;ticket.paymentType='payment_plan';const plan={id:nextId(plans),ticketId,frequency,paymentDay,firstDueDate,intervalDays:Math.max(1,Number(options.intervalDays)||30),numberOfPayments:Math.max(1,Number(options.numberOfPayments)||1),suggestedPaymentAmountCents:cents(options.suggestedPaymentAmount),downPaymentCents:cents(options.downPayment),surchargeType:options.surchargeType||'none',surchargeValue:Number(options.surchargeValue)||0,surchargeAmountCents:surcharge,basePriceCents:base,finalPriceCents:base+surcharge,createdAt:new Date().toISOString(),status:'active'};plans.push(plan);save('plans',plans);ticket.paymentPlanId=plan.id;persistTicket(ticket);generateSchedule(plan);if(plan.downPaymentCents>0)registerPayment({clientId:ticket.clientId,ticketId,amountCents:plan.downPaymentCents,date:today(),method:'Otro',reference:'Anticipo',notes:'Anticipo del plan',kind:'down_payment'});return plan}
function generateSchedule(plan){const schedules=get('schedules').filter(s=>s.paymentPlanId!==plan.id);const remainder=Math.max(0,plan.finalPriceCents-plan.downPaymentCents);let remaining=remainder;const interval=plan.frequency==='biweekly'?14:plan.frequency==='custom'?Number(plan.intervalDays||30):7;for(let i=0;i<plan.numberOfPayments;i++){const slots=plan.numberOfPayments-i;const amount=i===plan.numberOfPayments-1?remaining:(plan.suggestedPaymentAmountCents>0?Math.min(plan.suggestedPaymentAmountCents,remaining):Math.ceil(remaining/slots));schedules.push({id:nextId(schedules),paymentPlanId:plan.id,ticketId:plan.ticketId,dueDate:addDays(plan.firstDueDate,i*interval),expectedAmountCents:amount,coveredAmountCents:0,status:'pending'});remaining-=amount}save('schedules',schedules);refreshSchedules();return schedules.filter(s=>s.paymentPlanId===plan.id)}
function refreshSchedules(){const schedules=get('schedules');const payments=get('payments');const byTicket={};for(const payment of payments){if(payment.kind==='down_payment')continue;byTicket[payment.ticketId]=(byTicket[payment.ticketId]||0)+payment.amountCents}for(const schedule of schedules.sort((a,b)=>a.dueDate.localeCompare(b.dueDate))){const available=byTicket[schedule.ticketId]||0;const covered=Math.min(available,schedule.expectedAmountCents);schedule.coveredAmountCents=covered;byTicket[schedule.ticketId]=available-covered;schedule.status=covered>=schedule.expectedAmountCents?'paid':covered>0?'partial':schedule.dueDate<today()?'overdue':'pending'}save('schedules',schedules);return schedules}
function registerPayment(input){const list=get('payments');const ticket=get('tickets').find(t=>t.id===Number(input.ticketId||input.ticketId));if(!ticket)throw new Error('Ticket no encontrado.');const amountCents=input.amountCents!=null?Number(input.amountCents):cents(input.amount);if(amountCents<=0)throw new Error('El abono debe ser mayor a cero.');const payment={id:nextId(list),clientId:ticket.clientId,ticketId:ticket.id,amountCents,date:isoDate(input.date),method:input.method||'Otro',reference:input.reference||'',notes:input.notes||'',proofId:null,kind:input.kind||'payment',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};list.push(payment);save('payments',list);refreshSchedules();persistTicket(ticket);const c=calculate(ticket);if(c.unresolvedExcessCents>0)createCredit({clientId:ticket.clientId,type:'credit_created',amountCents:c.unresolvedExcessCents,sourceTicketId:ticket.id,reason:'Sobreabono'});return payment}
function createProof(paymentId,fileRecord){const payments=get('payments');const payment=payments.find(p=>p.id===paymentId);if(!payment)throw new Error('Abono no encontrado.');const proofs=get('proofs');const proof={id:nextId(proofs),clientId:payment.clientId,ticketId:payment.ticketId,paymentId,fileName:fileRecord.name,mimeType:fileRecord.type,size:fileRecord.size,dataUrl:fileRecord.dataUrl,createdAt:new Date().toISOString()};proofs.push(proof);save('proofs',proofs);payment.proofId=proof.id;save('payments',payments);return proof}
const FileRepository={maxBytes:750*1024,types:['image/jpeg','image/png','application/pdf'],read(file){return new Promise((resolve,reject)=>{if(!this.types.includes(file.type))return reject(new Error('Formato no permitido. Usa JPG, PNG o PDF.'));if(file.size>this.maxBytes)return reject(new Error('El comprobante supera 750 KB.'));const reader=new FileReader();reader.onerror=()=>reject(new Error('No se pudo leer el archivo.'));reader.onload=()=>resolve({name:file.name,type:file.type,size:file.size,dataUrl:reader.result});reader.readAsDataURL(file)})}};
function createCredit(input){const list=get('credits');const duplicate=input.sourceTicketId&&list.find(m=>m.type===input.type&&m.sourceTicketId===input.sourceTicketId&&m.amountCents===input.amountCents);if(duplicate)return duplicate;const movement={id:nextId(list),clientId:input.clientId,type:input.type,amountCents:Number(input.amountCents),sourceTicketId:input.sourceTicketId||null,destinationTicketId:input.destinationTicketId||null,reason:input.reason||'',createdAt:new Date().toISOString()};list.push(movement);save('credits',list);return movement}
function clientCreditCents(clientId){return get('credits').filter(m=>m.clientId===clientId).reduce((s,m)=>s+(m.type==='credit_created'||m.type==='credit_adjustment'?m.amountCents:-m.amountCents),0)}
function applyCredit(ticketId,amount){const ticket=get('tickets').find(t=>t.id===ticketId);if(!ticket)throw new Error('Ticket no encontrado.');const available=clientCreditCents(ticket.clientId);const apply=Math.min(cents(amount),available,calculate(ticket).balanceDueCents);if(apply<=0)throw new Error('No hay saldo aplicable.');createCredit({clientId:ticket.clientId,type:'credit_applied',amountCents:apply,destinationTicketId:ticket.id,reason:'Aplicado a ticket'});persistTicket(ticket);return apply}
function registerRefund(input){const ticket=get('tickets').find(t=>t.id===input.ticketId);if(!ticket)throw new Error('Ticket no encontrado.');const list=get('refunds');const refund={id:nextId(list),clientId:ticket.clientId,ticketId:ticket.id,orderItemId:input.orderItemId||null,amountCents:cents(input.amount),date:isoDate(input.date),method:input.method||'Transferencia',reason:input.reason||'',notes:input.notes||'',proofId:null,createdAt:new Date().toISOString()};if(refund.amountCents<=0)throw new Error('Monto inválido.');list.push(refund);save('refunds',list);persistTicket(ticket);return refund}
function resolveCancellation(orderId,resolution){const ticket=syncTicketForOrder(orderId);if(!ticket)return null;const excess=calculate(ticket).unresolvedExcessCents;if(excess<=0)return{ticket,excessCents:0};if(resolution==='refund')registerRefund({ticketId:ticket.id,amount:moneyValue(excess),reason:'Cancelación de producto'});else createCredit({clientId:ticket.clientId,type:'credit_created',amountCents:excess,sourceTicketId:ticket.id,reason:'Cancelación de producto'});persistTicket(ticket);return{ticket,excessCents:excess}}
function nextScheduledPayment(clientId){refreshSchedules();const ticketIds=get('tickets').filter(t=>t.clientId===clientId).map(t=>t.id);return get('schedules').filter(s=>ticketIds.includes(s.ticketId)&&s.status!=='paid').sort((a,b)=>a.dueDate.localeCompare(b.dueDate))[0]||null}
function migrate(){for(const k of Object.keys(keys))if(localStorage.getItem(keys[k])===null)save(k,[]);const templates=get('templates');if(!templates.length)save('templates',[{id:1,name:'Semanal — Viernes',frequency:'weekly',paymentDay:5,downPaymentPercent:0,surchargeType:'percent',surchargeValue:0,numberOfPayments:4},{id:2,name:'Quincenal',frequency:'biweekly',paymentDay:null,downPaymentPercent:0,surchargeType:'none',surchargeValue:0,numberOfPayments:2},{id:3,name:'50% + semanal',frequency:'weekly',paymentDay:5,downPaymentPercent:50,surchargeType:'none',surchargeValue:0,numberOfPayments:4},{id:4,name:'3 pagos',frequency:'custom',paymentDay:null,downPaymentPercent:0,surchargeType:'none',surchargeValue:0,numberOfPayments:3}]);for(const order of data.getOrders())createTicketFromOrder(order);localStorage.setItem('glamstudio_schema_version','6')}
const api={cents,moneyValue,today,addDays,dayDiff,getTickets:()=>get('tickets'),getPlans:()=>get('plans'),getSchedules:()=>refreshSchedules(),getPayments:()=>get('payments'),getProofs:()=>get('proofs'),getCredits:()=>get('credits'),getRefunds:()=>get('refunds'),getTemplates:()=>get('templates'),calculate,calculateTicketSubtotal:t=>activeSubtotal(t),calculateTicketTotal:t=>calculate(t).totalCents,calculateAmountPaid:t=>calculate(t).amountPaidCents,calculateBalanceDue:t=>calculate(t).balanceDueCents,calculateClientCredit:clientCreditCents,calculateFinancialStatus:financialStatus,getNextScheduledPayment:nextScheduledPayment,createTicketFromOrder,syncTicketForOrder,setTicketDiscount,setItemDiscount,createPlan,generateSchedule,refreshSchedules,registerPayment,createProof,FileRepository,createCredit,applyCredit,registerRefund,resolveCancellation,persistTicket,paymentsFor,refundsFor,overdueSchedules,formatMoney:c=>moneyValue(c).toLocaleString('es-MX',{style:'currency',currency:'MXN'}),formatDate:d=>new Date(d+'T12:00:00').toLocaleDateString('es-MX',{weekday:'short',day:'numeric',month:'short'})};
global.LuxuryFinance=api;migrate();
})(window);
