(function(global){'use strict';
const links=[['pedidos','Pedidos'],['tickets','Tickets'],['cobranza','Cobranza'],['clientes','Clientes'],['catalogo','Catálogo'],['por-ordenar','Por ordenar'],['en-camino','En camino'],['disponibles','Disponibles'],['agenda','Agenda']];
const modals=`
<div class="overlay" id="order-modal" style="display:none" onclick="closeModal('order-modal',event)"><div class="modal" onclick="event.stopPropagation()"><div class="modal-title" id="order-modal-title">Nuevo pedido</div><div class="field"><label>Clienta</label><input id="f-name"></div><div class="field"><label>WhatsApp</label><input id="f-phone"></div><div class="field"><label>Canal</label><select id="f-source"><option>WhatsApp</option><option>Instagram</option></select></div><div class="field"><label>Productos</label><input id="prod-search" placeholder="Buscar" oninput="filterProdOpts(this.value)"><div class="prod-selector" id="prod-selector"></div></div><div class="field"><label>Notas</label><textarea id="f-notes"></textarea></div><div class="modal-actions"><button class="btn-cancel-m" onclick="closeModal('order-modal')">Cancelar</button><button class="btn-primary" onclick="saveOrder()">Guardar</button></div></div></div>
<div class="overlay" id="sched-modal" style="display:none" onclick="closeModal('sched-modal',event)"><div class="modal" onclick="event.stopPropagation()"><div class="modal-title" id="sched-modal-title">Agendar entrega</div><div id="sched-aviso" class="aviso-box" style="display:none"></div><div class="loc-cards"><div class="loc-card" id="loc-indeco" onclick="selectLoc('indeco')"><div class="loc-name">Indeco de 8</div><div class="loc-hours">8:30 am – 12:30 pm</div></div><div class="loc-card" id="loc-villas" onclick="selectLoc('villas')"><div class="loc-name">Villas del Encanto</div><div class="loc-hours">4:00 pm – 8:00 pm</div></div></div><div class="field"><label>Fecha</label><input type="date" id="sched-date" onchange="updateSlots()"></div><div class="field" id="slots-wrap" style="display:none"><label>Horario</label><div id="time-slots" class="slots"></div></div><div class="field"><label>Notas</label><textarea id="sched-notes"></textarea></div><div class="modal-actions"><button class="btn-cancel-m" onclick="closeModal('sched-modal')">Cancelar</button><button class="btn-primary" onclick="saveSchedule()">Confirmar</button></div></div></div>
<div class="overlay" id="cancel-entrega-modal" style="display:none" onclick="closeModal('cancel-entrega-modal',event)"><div class="modal" onclick="event.stopPropagation()"><div class="modal-title">Cancelar entrega</div><div class="field"><label>Motivo</label><textarea id="cancel-reason"></textarea></div><div class="modal-actions"><button class="btn-cancel-m" onclick="closeModal('cancel-entrega-modal')">Cerrar</button><button class="btn-primary" onclick="confirmCancelEntrega()">Cancelar y avisar</button></div></div></div>
<div class="overlay" id="cancel-modal" style="display:none" onclick="closeModal('cancel-modal',event)"><div class="modal" onclick="event.stopPropagation()"><div class="modal-title">Cancelar productos</div><div id="cancel-prod-list" class="cancel-prod-list"></div><div class="field"><label>Si existe dinero pagado de más</label><select id="cancel-financial-resolution"><option value="credit">Crear saldo a favor</option><option value="refund">Registrar reembolso</option></select></div><div class="modal-actions"><button class="btn-cancel-m" onclick="closeModal('cancel-modal')">Cerrar</button><button class="btn-primary" onclick="confirmCancelProds()">Cancelar y notificar</button></div></div></div>
<div class="overlay" id="prod-modal" style="display:none" onclick="closeModal('prod-modal',event)"><div class="modal" onclick="event.stopPropagation()"><div class="modal-title">Producto</div><div class="field"><label>Nombre</label><input id="p-name"></div><div class="field"><label>Precio</label><input type="number" id="p-price"></div><div class="field"><label>Emoji</label><input id="p-emoji"></div><div class="field"><label>Categoría</label><input id="p-cat"></div><div class="field"><label>Stock</label><select id="p-stock"><option value="1">Disponible</option><option value="0">Agotado</option></select></div><div class="modal-actions"><button class="btn-cancel-m" onclick="closeModal('prod-modal')">Cancelar</button><button class="btn-primary" onclick="saveProduct()">Guardar</button></div></div></div>
<div class="overlay" id="client-modal" style="display:none" onclick="closeModal('client-modal',event)"><div class="modal" onclick="event.stopPropagation()"><div id="client-modal-title" class="modal-title">Nueva clienta</div><div class="field"><label>Nombre</label><input id="c-name"></div><div class="field"><label>Celular</label><input id="c-phone"></div><div class="field"><label>WhatsApp</label><input id="c-whatsapp"></div><div class="field"><label>Instagram</label><input id="c-instagram"></div><div class="field"><label>Email</label><input id="c-email" type="email"></div><div class="field"><label>Notas</label><textarea id="c-notes"></textarea></div><div class="modal-actions"><button class="btn-cancel-m" onclick="closeModal('client-modal')">Cancelar</button><button class="btn-primary" onclick="saveClient()">Guardar</button></div></div></div>
<div class="overlay" id="client-detail-modal" style="display:none" onclick="closeModal('client-detail-modal',event)"><div class="modal client-detail-modal" onclick="event.stopPropagation()"><div id="client-detail-content"></div><div class="modal-actions"><button class="btn-cancel-m" onclick="closeModal('client-detail-modal')">Cerrar</button></div></div></div><div class="toast" id="toast"></div>`;
global.AdminShell={mount(page,content){document.write(`<div class="app"><div class="topbar"><a class="logo" href="index.html">luxury<span>finds</span></a><div class="nav">${links.map(([key,label])=>`<a class="${key===page?'active':''}" href="${key}.html">${label}</a>`).join('')}</div></div>${content}</div>${modals}`)}};
})(window);
